### ISSUE TITLE
muqy_20240101_2Bgeoprof_reader 这个文件好像没给出来？

### ISSUE THREAD

**Issue by benerain** [muqingyu666/Project_cirrus_classification#1]
我在研究读取和可视化cloudsat/calipso数据，但是在读取过程中遇到了问题，想参考一下你是怎么读取的

**Comment by muqingyu666** [comment]
具体是什么问题呢，使用的CloudSat level几的产品？

**Comment by benerain** [comment]
想可视化2B-CLDCLASS-LIDAR的cloud layer base， 读1D数据的时候出了点问题

**Comment by benerain** [comment]
具体问题就是用h5py读的时候，只有2D数据能在hdf.keys()显示
```py
with HDF(filename) as hdf:
    datasets = hdf.keys()
    print(datasets)
```
lat lon 和time都没有。只有2D的

**Comment by benerain** [comment]
方便的话可以加 vx吗？我是国家气象局人影中心这边的新员工，刚刚接触气象这块。lyj11235813LYJ。
